In [ ]:
import os
import pymssql

import pandas as pd
import numpy as np

from dotenv import load_dotenv
from utils_ccd import get_connection

load_dotenv()
conn = get_connection()

In [4]:
descontos_sql = ''' SELECT pro.numero_processo,
       pro.ano_processo,
       pm.Descricao
FROM processo.dbo.Processos pro
INNER JOIN processo.dbo.Pro_MarcadorProcesso pmp ON pmp.IdProcesso = pro.IdProcesso
INNER JOIN processo.dbo.Pro_Marcador pm ON pmp.IdMarcador = pm.IdMarcador 
WHERE pro.setor_atual = 'CCD'
AND lower(pm.Descricao) = 'DESCONTO EM FOLHA'
'''
processos_descontos = pd.read_sql(descontos_sql, conn)

/tmp/ipykernel_93107/4246048530.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  processos_descontos = pd.read_sql(descontos_sql, conn)

In [5]:
processos_descontos

   numero_processo ano_processo          Descricao
0           011032         2016  DESCONTO EM FOLHA
1           017229         2017  DESCONTO EM FOLHA
2           002138         2019  DESCONTO EM FOLHA
3           000088         2021  DESCONTO EM FOLHA
4           002696         2022  DESCONTO EM FOLHA
5           000454         2024  DESCONTO EM FOLHA
6           000455         2024  DESCONTO EM FOLHA
7           000457         2024  DESCONTO EM FOLHA
8           000459         2024  DESCONTO EM FOLHA
9           000460         2024  DESCONTO EM FOLHA
10          000461         2024  DESCONTO EM FOLHA
11          000478         2024  DESCONTO EM FOLHA
12          002015         2024  DESCONTO EM FOLHA
13          002016         2024  DESCONTO EM FOLHA
14          002031         2024  DESCONTO EM FOLHA
15          002033         2024  DESCONTO EM FOLHA
16          002035         2024  DESCONTO EM FOLHA
17          002036         2024  DESCONTO EM FOLHA
18          002570         2024  DESCONTO EM FOLHA
19          002573         2024  DESCONTO EM FOLHA
20          002574         2024  DESCONTO EM FOLHA
21          002594         2024  DESCONTO EM FOLHA
22          002595         2024  DESCONTO EM FOLHA
23          003367         2024  DESCONTO EM FOLHA
24          003368         2024  DESCONTO EM FOLHA
25          003391         2024  DESCONTO EM FOLHA
26          003393         2024  DESCONTO EM FOLHA
27          003396         2024  DESCONTO EM FOLHA
28          003398         2024  DESCONTO EM FOLHA
29          003406         2024  DESCONTO EM FOLHA
30          003408         2024  DESCONTO EM FOLHA
31          003411         2024  DESCONTO EM FOLHA
32          003414         2024  DESCONTO EM FOLHA
33          003419         2024  DESCONTO EM FOLHA
34          004772         2024  DESCONTO EM FOLHA
35          004773         2024  DESCONTO EM FOLHA
36          004867         2024  DESCONTO EM FOLHA
37          004876         2024  DESCONTO EM FOLHA
38          004886         2024  DESCONTO EM FOLHA
39          004888         2024  DESCONTO EM FOLHA
40          004893         2024  DESCONTO EM FOLHA
41          004896         2024  DESCONTO EM FOLHA
42          004903         2024  DESCONTO EM FOLHA
43          004923         2024  DESCONTO EM FOLHA