In [1]:
import os
import pymssql

import pandas as pd
import numpy as np

from dotenv import load_dotenv
from utils_ccd import get_connection

load_dotenv()
conn = get_connection()

In [2]:
descontos_sql = ''' 

SELECT DISTINCT pro.numero_processo,
       pro.ano_processo,
       pro.assunto,
       pm.Descricao,
       gp.Nome,
       processo.dbo.fn_Exe_RetornaValorAtualizado(ed.IdDebito),
       (
       	SELECT top 1 vspfr.nomeorgao
       	FROM BdDIP.dbo.vwSiaiPessoalFolhaResumida vspfr 
       	WHERE vspfr.cpf  = gp.Documento COLLATE SQL_Latin1_General_CP1_CI_AS
       ) 
       
FROM processo.dbo.Processos pro
INNER JOIN processo.dbo.Pro_MarcadorProcesso pmp ON pmp.IdProcesso = pro.IdProcesso
INNER JOIN processo.dbo.Pro_Marcador pm ON pmp.IdMarcador = pm.IdMarcador
LEFT JOIN processo.dbo.Exe_Debito ed ON ed.IdProcessoExecucao = pro.IdProcesso
LEFT JOIN processo.dbo.Exe_DebitoPessoa edp ON edp.IDDebito = ed.IdDebito
LEFT JOIN processo.dbo.GenPessoa gp ON gp.IdPessoa = edp.IDPessoa
WHERE pro.setor_atual = 'CCD'
AND lower(pm.Descricao) = 'DESCONTO EM FOLHA'

'''
processos_descontos = pd.read_sql(descontos_sql, conn)

/tmp/ipykernel_11864/734101892.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  processos_descontos = pd.read_sql(descontos_sql, conn)

DatabaseError: Execution failed on sql '

SELECT DISTINCT pro.numero_processo,
       pro.ano_processo,
       pro.assunto,
       pm.Descricao,
       gp.Nome,
       processo.dbo.fn_Exe_RetornaValorAtualizado(ed.IdDebito),
       (
       	SELECT top 1 vspfr.nomeorgao
       	FROM BdDIP.dbo.vwSiaiPessoalFolhaResumida vspfr
       	WHERE vspfr.cpf  = gp.Documento COLLATE SQL_Latin1_General_CP1_CI_AS
       )

FROM processo.dbo.Processos pro
INNER JOIN processo.dbo.Pro_MarcadorProcesso pmp ON pmp.IdProcesso = pro.IdProcesso
INNER JOIN processo.dbo.Pro_Marcador pm ON pmp.IdMarcador = pm.IdMarcador
LEFT JOIN processo.dbo.Exe_Debito ed ON ed.IdProcessoExecucao = pro.IdProcesso
LEFT JOIN processo.dbo.Exe_DebitoPessoa edp ON edp.IDDebito = ed.IdDebito
LEFT JOIN processo.dbo.GenPessoa gp ON gp.IdPessoa = edp.IDPessoa
WHERE pro.setor_atual = 'CCD'
AND lower(pm.Descricao) = 'DESCONTO EM FOLHA'

': (207, b"Invalid column name 'nomeorgao'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

In [11]:
processos_descontos

,numero_processo,ano_processo,Descricao,Nome,Documento
0,000088,2021,DESCONTO EM FOLHA,José Miguel de Menezes Júnior,28927265491
1,000088,2021,DESCONTO EM FOLHA,JOSINALDO AMARO DE LIMA,73694940472
2,000454,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
3,000455,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
4,000457,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
5,000459,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
6,000460,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
7,000461,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
8,000478,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
9,002015,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
10,002016,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
11,002031,2024,DESCONTO EM FOLHA,RICHARDSON XAVIER CUNHA,50149806434
12,002033,2024,DESCONTO EM FOLHA,HAROLDO GOMES DA SILVA,45536996487
13,002035,2024,DESCONTO EM FOLHA,HAROLDO GOMES DA SILVA,45536996487
14,002036,2024,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
15,002138,2019,DESCONTO EM FOLHA,LUDMILA CARLOS AMORIM DE ARAÚJO ROSADO,01186793414
16,002138,2019,DESCONTO EM FOLHA,ABEL BELARMINO DE AMORIM FILHO,30732921449
17,002570,2024,DESCONTO EM FOLHA,ERALDO ALVES DE ARAÚJO (VEREADOR),93755228491
18,002573,2024,DESCONTO EM FOLHA,JOSÉ BARBOSA,30806348453
19,002574,2024,DESCONTO EM FOLHA,Josemar Ferreira bezerra,96636823453
20,002594,2024,DESCONTO EM FOLHA,"José Aracleide de Araújo, Prefeito",66416841487
21,002595,2024,DESCONTO EM FOLHA,Clevilandia Samara de Vasconcelos Belarmino (A...,08951902498
22,002696,2022,DESCONTO EM FOLHA,Nereu Batista Linhares - Presidente do Ipern,13006444434
23,003367,2024,DESCONTO EM FOLHA,JOSÉ RIBAMAR LEITE NÓBREGA (VICE PREFEITO),02140437462
24,003368,2024,DESCONTO EM FOLHA,Alexandre Pereira de Araujo Montenegro(vereador),07227091457
25,003391,2024,DESCONTO EM FOLHA,FRANCISCO ANTONIO FAUSTINO,00892716452
26,003393,2024,DESCONTO EM FOLHA,"José Aracleide de Araújo, Prefeito",66416841487
27,003396,2024,DESCONTO EM FOLHA,FRANCISCO DAS CHAGAS DE MEDEIROS,14077485487
28,003396,2024,DESCONTO EM FOLHA,Jailson José da Silva,64275574400
29,003398,2024,DESCONTO EM FOLHA,JOSÉ ANTÔNIO DE MENEZES SOUZA (ATUAL PREFEITO),13098608404
30,003406,2024,DESCONTO EM FOLHA,JOSÉ ROBERTO DE SOUZA,80727468472
31,003408,2024,DESCONTO EM FOLHA,EUGÊNIO GALVÃO GONDIM,17011612491
32,003411,2024,DESCONTO EM FOLHA,Eudes Miranda da Fonseca (vereador ),90455088420
33,003414,2024,DESCONTO EM FOLHA,PEDRO HOLANDA FILHO,05030943404
34,003414,2024,DESCONTO EM FOLHA,NELSON HERMÓGENES DE MEDEIROS FREIRE,06714080468
35,004923,2024,DESCONTO EM FOLHA,"SONYARA DE SOUZA RIBEIRO, PREFEITA",01083240447
36,011032,2016,DESCONTO EM FOLHA,CARLOS JOSÉ FERNANDES,76816591453
37,017229,2017,DESCONTO EM FOLHA,None,None